# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Profiles/Administrator/Desktop/Tetris/display/display.cache/wt [current_project]
set_property parent.project_path D:/Profiles/Administrator/Desktop/Tetris/display/display.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo d:/Profiles/Administrator/Desktop/Tetris/display/display.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/Profiles/Administrator/Desktop/Tetris/display/display.srcs/sources_1/new/display.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Profiles/Administrator/Desktop/Tetris/display/display.srcs/constrs_1/new/display.xdc
set_property used_in_implementation false [get_files D:/Profiles/Administrator/Desktop/Tetris/display/display.srcs/constrs_1/new/display.xdc]


synth_design -top vga_test -part xc7z020clg484-1


write_checkpoint -force -noxdef vga_test.dcp

catch { report_utilization -file vga_test_utilization_synth.rpt -pb vga_test_utilization_synth.pb }
