# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Profiles/Administrator/Desktop/Tetris/main/main.runs/synth_1/.Xil/Vivado-5400-1004-9020-1819-017/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      D:/Profiles/Administrator/Desktop/Tetris/main/main.srcs/sources_1/new/main.vhd
      D:/Profiles/Administrator/Desktop/Tetris/main/main.srcs/sources_1/new/falling_block_decode.vhd
      D:/Profiles/Administrator/Desktop/Tetris/main/main.srcs/sources_1/new/falling.vhd
      D:/Profiles/Administrator/Desktop/Tetris/main/main.srcs/sources_1/imports/keyboard/PmodKYPD.vhd
      D:/Profiles/Administrator/Desktop/Tetris/main/main.srcs/sources_1/imports/keyboard/DisplayController.vhd
      D:/Profiles/Administrator/Desktop/Tetris/main/main.srcs/sources_1/imports/keyboard/Decoder.vhd
      D:/Profiles/Administrator/Desktop/Tetris/main/main.srcs/sources_1/new/move.vhd
      D:/Profiles/Administrator/Desktop/Tetris/main/main.srcs/sources_1/imports/new/display.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/Profiles/Administrator/Desktop/Tetris/main/main.runs/synth_1/.Xil/Vivado-5400-1004-9020-1819-017/realtime/main_synth.xdc
    rt::sdcChecksum
    set rt::top main
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/Profiles/Administrator/Desktop/Tetris/main/main.cache/wt}
    rt::set_parameter enableSplitFlowPath "D:/Profiles/Administrator/Desktop/Tetris/main/main.runs/synth_1/.Xil/Vivado-5400-1004-9020-1819-017/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
